### ISSUE TITLE
build instructions

### ISSUE THREAD

**Issue by RoboMWM** [BenWoodworth/FastCraft#101]
How do we build this project? I'm familiar with maven projects, and you seemed to have flat-out removed the pom.

It also seems you have removed the gradle wrapper...

**Comment by BenWoodworth** [comment]
I'm building the plugin up from scratch because of a few fundamental flaws making it very difficult to fix some bugs, so building the latest commit won't yield a working jar. I'll be sure to re-add the Gradle wrapper.

You can find the source to the latest release here (which includes the pom):
https://github.com/BenWoodworth/FastCraft/tree/v0.26.5
