### ISSUE TITLE
Leather Cap recipe bugged

### ISSUE THREAD

**Issue by ViscousSummer88** [BenWoodworth/FastCraft#116]
## Description
When trying to craft a leather cap with fastcraft+ it required the ingredients of a leather cap meaning you're unable to craft the item with leather. 

Screenshot: https://cdn.discordapp.com/attachments/346898045436297218/351278807992369162/unknown.png

## Reproduction
- Put leather in your inventory and try to craft using fastcraft+ a leather cap.
- Put a leather cap in your inventory and you will see the option to craft a letaher cap
- ...

## Output/Files
- None.

## Server Details
- FastCraft Version: v0.27.2
- Server Version: BUKKIT/SPIGOT/SPONGE Build 61

**Comment by CloudeLecaw** [comment]
This is a problem of your server config or a custom recipe you created
see here...all is fine
Fastcraft Version 0.27.2 and Spigot 1.12.1
![image](https://user-images.githubusercontent.com/12080017/30002235-5d397666-90a4-11e7-8e2e-9c558016eb20.png)

**Comment by Jikoo** [comment]
Actually, it's the repair recipe for combining 2 items to restore durability.

**Comment by CloudeLecaw** [comment]
repair items not apeair in the GUi ..the gui is not ready fort this... the question is why it apears to you? look at the screenshot - u see all is fine and the right recipe for the leather cap is shown...so what causes the error/issues on your servers?

What servers your using?
üls try Spigot 1.12.1 with Fastcraft 0.27.2 and a permissionsystem like PEX and without custom recipes to see if this issues still exist then on your server...

**Comment by BenWoodworth** [comment]
It does appear to be a repair recipe. I hard-code recipe hash codes that should be ignored, since the Bukkit API has no way of checking the resulting item of a 'Recipe' given certain ingredients. If the repair recipe's hash code changed in 1.12, it would no longer be ignored.

There were a lot of breaking changes in 1.12 (achievements are gone, recipes have changed, etc.), so FastCraft isn't fully compatible. I'm in the process of developing FastCraft v1, which will support 1.12 and newer, and will resolve this issue.

For now you can blacklist the recipe, so it doesn't appear in FastCraft:
https://github.com/BenWoodworth/FastCraft/wiki/Blacklisting-Recipes

**Comment by BenWoodworth** [comment]
Fixed for the next release :smile:
