### ISSUE TITLE
Compatibility - RecipeManager

### ISSUE THREAD

**Issue by SoSeDiK** [BenWoodworth/FastCraft#123]
1. In crafting preview and after crafting there is a lore 'RecipeManager #\<numbers\>'. It should be hidden.
2. Support for RecipeManager's flags (specific name, lore, command after crafting etc).

For example:
Regular workbench:
![](https://image.prntscr.com/image/bQdmUFPjScWTuNJGFt06Mw.png)
FastCraft+:
![](https://image.prntscr.com/image/Y3c2EPY3TIyFWrLTPhIXiQ.png)

Plugin:
https://github.com/haveric/RecipeManager2

**Comment by CloudeLecaw** [comment]
Together with CustomRecipes:
Example:
- Call an Item TestSubject - lets say a Stone that you call "TestMaterial"
- Now create a TestItem- lets say a Flint&Steeö that you call "Test Item"
- Now create a custom shaped Recipe - lets say with the Key 100 while holing the TestItem
   for Materials you now use some of you TestMaterials
- Now take some normal Stones into yourInventory
- Open the Fastcraftworkbench....
Result: you will find the Item TestItem there...but it says it just require normal Stone...
if you klick it the normal stone is taken from your inventory and you got the TestItem..


This little "bug" ruins servers that work with modified blocks for crafting...

![1](https://user-images.githubusercontent.com/12080017/34246376-a4c6d002-e62e-11e7-8131-39c7f7a394f3.jpg)
Create a CustomRecipe with a Special Material​​

![2](https://user-images.githubusercontent.com/12080017/34246389-ac28e1c8-e62e-11e7-940a-05434a5d6927.jpg)
get the simly item of it (in this case stone)

![3](https://user-images.githubusercontent.com/12080017/34246396-b1913eb2-e62e-11e7-806d-18511d27996e.jpg)
Choose the SpecialItem from your FastCraft Inventory

![4](https://user-images.githubusercontent.com/12080017/34246403-b96dad50-e62e-11e7-8a9b-e930e034f0d5.jpg)
Here you have it...u payed normal stone for the Special item instead of the special material..

**Comment by BenWoodworth** [comment]
Could you test compatibility with [the latest release](https://github.com/BenWoodworth/FastCraft/releases)?

**Comment by CloudeLecaw** [comment]
Where to download? im not comfirmal with using git and all these things ;3

**Comment by BenWoodworth** [comment]
You can find it here :)
https://github.com/BenWoodworth/FastCraft/releases
