### ISSUE TITLE
Compatibility issue with ProRecipes

### ISSUE THREAD

**Issue by Deathinflames** [BenWoodworth/FastCraft#143]
## Description
I noticed this stack trace in my server logs and while things still seem to work fine as far as i can tell, there apparently is a API issue with FastCraft + ProRecipes.

## Reproduction
- Load FastCraft v2.0.3 and ProRecipes v2.1.4 on Spigot 1.12.2.

## Output/Files
- Stack Trace: https://pastebin.com/raw/1u6t4P8M
- `/fcadmin debug`: no output
- RELEVANT CONFIGS: N/A

## Server Details
- FastCraft Version: v2.0.3
- Server Version: SPIGOT 1.12.2
- RELEVANT PLUGINS: FastCraft + ProRecipes

**Comment by BenWoodworth** [comment]
I can't figure out why you're getting this error just, looking at the ProRecipes source.

I know about 4 months ago, the packages in ProRecipes were moved around:
https://github.com/mcgrizzz/ProRecipes/commit/448cfcbc58bd2b3dcd13bc129c2cfe465bfda808

And then changed back later because it broke its API:
https://github.com/mcgrizzz/ProRecipes/commit/791515963807e7ce0655d3ee986760ac894521b8

Could you check in your ProRecipes.jar to see if it contains a `me` or `mc` folder at its root? If it's `me`, then that's what's causing the issue.

![screenshot from 2018-09-29 23-17-24](https://user-images.githubusercontent.com/1829157/46252913-e511d380-c43d-11e8-9757-0668afdb2cb1.png)

**Comment by Deathinflames** [comment]
That's strange, There does appear to be a mc folder at the root of the ProRecipes.jar.

![d28542d5acbeb30724a902c63c30df7b](https://user-images.githubusercontent.com/6750890/48726449-9e925700-ebec-11e8-9020-78d114cedbe8.png)

**Comment by BenWoodworth** [comment]
I think I found the issue. It looks like he moved the API classes into a .api package in the first commit (a breaking change), but didn't undo it when he fixed the packages in the second commit.

So, FastCraft is looking for
`me.mcgrizzz.prorecipes.RecipeAPI`, when it's actually at
`me.mcgrizzz.prorecipes.api.RecipeAPI`.

I'll leave a comment over at https://github.com/mcgrizzz/ProRecipes/issues/29 about it, because that seems to be the issue.
