### ISSUE TITLE
Increment minecraft:interact_with_crafting_table statistic

### ISSUE THREAD

**Issue by SlimeDog** [BenWoodworth/FastCraft#181]
## Description
FC interactions do not increment statistics `minecraft:interact_with_crafting_table`. Should it do?

The following recipe uses [StatisticEditor](https://www.spigotmc.org/resources/statisticeditor.75573/) in-game, which I find a useful tool. The client `statistics` window, or any other method of viewing player statistics, will serve.

Recipe:
- Install [StatisticEditor](https://www.spigotmc.org/resources/statisticeditor.75573/)
- /stats <player> CRAFTING_TABLE_INTERACTION
- /fc craft
- Craft any item
- /stats <player> CRAFTING_TABLE_INTERACTION
- Observe that counter has not changed

## Server Details
- Server: 1.16.1
- FastCraft: v3.2.3

## More Information
Note that `minecraft:crafted` statistic for the crated item is incremented correctly.

**Comment by BenWoodworth** [comment]
I did some playing around, and it looks like the `CRAFTING_TABLE_INTERACTION` stat counts the times players right click a crafting table block. So `/fc craft` shouldn't increment this stat, but the stat should incremented when opening FastCraft by right clicking a crafting table (which doesn't happen at the moment, because FastCraft is cancelling the `PlayerInteractEvent`). I should be able to get a fix for this in a day or two
