### ISSUE TITLE
Any slab variant is miscalculated. (1.16.4)

### ISSUE THREAD

**Issue by SrBedrock** [BenWoodworth/FastCraft#188]
## Description

Any slab variant is miscalculated.
Correct calculation: 1 item = 2 slabs variants

#### Example with oak plank

- Workbench: 6 packs of oak plank = 768 slabs of oak_plank

- FastCraft: 6 packs of oak plank = 656 slabs of oak_plank

## Server Details

- Server: `Purpur version git-Purpur-952 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)`

- FastCraft: `3.2.8`

**Comment by BenWoodworth** [comment]
How are you crafting the planks?

The stone slab ingredients look right when crafting 60, for example:
![image](https://user-images.githubusercontent.com/1829157/104834803-cb476500-586f-11eb-96f4-88ce052a6395.png)

**Comment by SrBedrock** [comment]
### Crafting stone slabs with fastcraft: (60 x 2 = 90 slabs)

https://user-images.githubusercontent.com/51332006/104835265-40bd3080-5884-11eb-8cb1-47ee129237ed.mp4


### Crafting stone slabs with fastcraft: (6 x 21 = 126 slabs)

https://user-images.githubusercontent.com/51332006/104835199-c7bdd900-5883-11eb-80c4-fd4e50fc98b8.mp4

### Crafting stone slabs with workbench: (126 slabs)

https://user-images.githubusercontent.com/51332006/104835083-e1125580-5882-11eb-8113-0f61d34b3d61.mp4

**Comment by BenWoodworth** [comment]
I played around with it a bit, and it looks like it can happen to basically any recipe that crafts >1 item

- Take sticks for example. Put 1 less than a full stack of sticks in your inventory (63).
- Set FastCraft's craft amount to craft >1x the normal amount (e.g. 8 instead of 4 sticks)
- Craft the sticks

![image](https://user-images.githubusercontent.com/1829157/104855687-2c0c8700-58dc-11eb-8f16-20a9968feb11.png)![image](https://user-images.githubusercontent.com/1829157/104855706-42b2de00-58dc-11eb-8cfc-e50752e1464d.png)

There should be 64+7 sticks, but one is missing. Now to dive into the code to see what's causing this...

**Comment by BenWoodworth** [comment]
Fixed! Basically an ItemStack(4x stick) was being added to the inventory twice, but Bukkit was changing its size to 3 (and changing the 63 stack to 64) the first time, so the second time it was adding 3 instead of 4.

**Comment by BenWoodworth** [comment]
Just posted v3.2.9 with the fix. Thanks for reporting this! :)
